name = "discord-bot-proxy"
compatibility_date = "2024-01-01"
workers_dev = true

main = "src/index.js"

[[durable_objects.bindings]]
name = "DISCORD_BOTS"
class_name = "DiscordBot"

[[migrations]]
tag = "v1"
new_classes = ["DiscordBot"]
